modLoader = "javafml"
loaderVersion = "[43,)"
license = "GPLv3"
issueTrackerURL = "https://github.com/Dan-Mizu/Vanillaful/issues"

[[mods]]
modId = "vanillaful"
version = "${version}"
displayName = "Vanillaful"
displayURL = "https://github.com/Dan-Mizu/Vanillaful"
logoFile = "assets/vanillaful/textures/gui/icon/icon.png"
authors = "DanMizu"
description = '''
An Extension of Vanilla Minecraft
'''

[[dependencies.vanillaful]]
modId = "forge"
mandatory = true
versionRange = "[43.1.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vanillaful]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vanillaful]]
modId = "botarium"
mandatory = true
versionRange = "[${botarium_version},)"
ordering = "NONE"
side = "BOTH"