modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId = "vanillaful"
version = "${version}"
displayName = "Vanillaful"
authors = "DanMizu"
description = '''
An Extension of Vanilla Minecraft
'''
#logoFile = "assets/vanillaful/textures/gui/icon/icon.png"

[[dependencies.vanillaful]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vanillaful]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vanillaful]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"